[package]
name = "emulator6502"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# This will look in src/lib.rs
name = "emulator6502"


[dependencies]
bitflags = "1.3.2"
